
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  datasource:
    username: root
    password: m1234567
    url: jdbc:mysql://192.168.31.52:3306/manage
    driver-class-name: com.mysql.jdbc.Driver