spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  security:
    user:
      name: root
      password: 12345678
  datasource:
    username: root
    password: m1234567
    url: jdbc:mysql://49.232.189.67:3306/manage
    driver-class-name: com.mysql.jdbc.Driver

